# Generated by Django 3.1.7 on 2021-02-20 20:33

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210220_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=['first_name', models.CharField(max_length=255)], unique=True),
        ),
    ]
