# Generated by Django 3.1.7 on 2021-02-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
