# Generated by Django 3.1.7 on 2021-02-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20210222_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=50)),
                ('humidity', models.CharField(max_length=50)),
                ('last_date', models.DateField()),
                ('last_hour', models.TimeField()),
                ('user_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'sensor_value',
                'verbose_name_plural': 'sensor_values',
            },
        ),
    ]
