# Generated by Django 3.1.7 on 2021-02-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_sensorvalues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorValues',
            new_name='SensorValue',
        ),
    ]
