# Generated by Django 3.1.7 on 2021-02-22 18:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20210222_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='sensor_name', unique=True),
        ),
    ]
