# Generated by Django 3.1.7 on 2021-02-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20210223_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
